### ISSUE TITLE
unittests "Aborted (core dumped)"

### ISSUE THREAD

**Issue by MaximilienNaveau** [machines-in-motion/real_time_tools#8]
During the continuous build we have these kind of issues (see below).
Anyone has an idea where this comes from?
```
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	[       OK ] threadsafe_timeseries.full_history (19236 ms)
build	23-Sep-2019 17:04:49	[ RUN      ] threadsafe_timeseries.partial_history
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
```
**error	23-Sep-2019 17:04:49	terminate called after throwing an instance of 'std::invalid_argument'**
```
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
```
**error	23-Sep-2019 17:04:49	what():  you tried to access timeseries element which is too old.**
```
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
build	23-Sep-2019 17:04:49	Warning this thread is not going to be real time.
error	23-Sep-2019 17:04:52	Aborted (core dumped)
```

**Comment by wumanu** [comment]
this means most likely that the thread which reads from the timeseries [https://github.com/machines-in-motion/real_time_tools/blob/master/tests/threadsafe_timeseries_test.cpp#L23](url) is too slow. 

i am a bit surprised this happens (even on a non-realtime machine), since the other thread [https://github.com/machines-in-motion/real_time_tools/blob/master/tests/threadsafe_timeseries_test.cpp#L117](url) waits at each iteration, and there is a buffer of 100 in the timeseries [https://github.com/machines-in-motion/real_time_tools/blob/master/tests/threadsafe_timeseries_test.cpp#L128](url).

also, it is weird that this happens now after your changes (they looked ok to me). did you run the tests before and after the changes you made?

**Comment by MaximilienNaveau** [comment]
You actually start the reader before the publisher no?

**Comment by wumanu** [comment]
yes, so it seems like the readers for some reason cannot keep up with the publisher

**Comment by MaximilienNaveau** [comment]
Ok. This error appear only in the docker in Bamboo.
On my computer unit-tests when fine before and after my modifications.

**Comment by MaximilienNaveau** [comment]
Ok, I think the error comes from the fact that you used global variables and that they where not re-initialized between the 2 tests.

**Comment by wumanu** [comment]
i don't see what you mean, at the beginning of each test the inputs are initialized and the timeseries is initialized, right?

**Comment by MaximilienNaveau** [comment]
Solution: to the problem, increase the sleeping duration in the slow thread
